#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd as an history
file="/etc/passwd"
while IFS= read -r line
do
        oldIFS="$IFS"
	IFS=":"
	set -- $line
        echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"
done < "$file"
